typography_spectrum: 0.5618014284409583
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.24636249849572778
  lightness: 0.9018414588645101
  saturation: 0.24675277224741876
  rhythmicContrast: 0.14841309026814997
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.09703210578300059
analytics:
  google: UA-8089221-1
  facebook: null
  twitter: null
author:
  name: Shaine Mata
  email: shaine@shainemata.com
  url: 'http://www.shainemata.com'
name: Shaine Mata
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: cb9af48e-2762-485a-9dc2-170512b679c2
    type: content
  - name: FIRE Blog Gallery
    url: 'http://fireblog.gallery'
    type: external
favicon: null
title: Shaine Mata
content: []
description: Seeking Freedom
purpose:
  - type: contact
    url: 'tel:19562050706'
    label: Call Me
