typography_spectrum: 0.5618014284409583
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.24636249849572778
  lightness: 0.9018414588645101
  saturation: 0.24675277224741876
  rhythmicContrast: 0.14841309026814997
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.09703210578300059
analytics:
  google: UA-8089221-1
  facebook: null
  twitter: null
author:
  name: Shaine Mata
  email: shaine@shainemata.com
  url: 'http://www.shainemata.com'
name: Shaine Mata
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    url: 'http://www.shainemata.com'
    type: external
  - name: About
    id: cb9af48e-2762-485a-9dc2-170512b679c2
    type: content
  - name: Contact
    id: bbcf56ef-66a8-4c5f-a5bf-da2f61131422
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/Shaine.Lee.Mata/'
    type: external
  - name: G+
    url: 'https://plus.google.com/u/0/+ShaineMata'
    type: external
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/shainemata'
    type: external
favicon: null
title: Shaine Mata
description: Seeking Freedom
purpose: []
