name: shaine
favicon: null
layout_spectrum: 0.83846
typography_spectrum: 0.29939
title: Shaine Mata
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-8089221-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#310911'
    - '#d7dfe1'
    - '#9a9da2'
    - '#6e1a2a'
    - '#64676c'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
