typography_spectrum: 0.29939
color:
  brandColors:
    - '#310911'
    - '#d7dfe1'
    - '#9a9da2'
    - '#6e1a2a'
    - '#64676c'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74364
analytics:
  google: UA-8089221-1
  facebook: null
  twitter: null
author:
  name: Shaine Mata
  email: shaine@shainemata.com
  url: 'http://www.shainemata.com'
name: shaine
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: cb9af48e-2762-485a-9dc2-170512b679c2
    type: content
favicon: null
title: Shaine Mata
description: Mystic Geek
purpose:
  - name: null
    item: null
    url: null
