name: shaine
favicon: null
layout_spectrum: 0.77699
typography_spectrum: 0.07463
title: Shaine Mata
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-8089221-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5d6d6c'
    - '#93b7c7'
    - '#778f99'
    - '#101417'
    - '#2e4763'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.896396
purpose:
  - name: null
    item: null
    url: null
